#!/bin/bash


fecha=$(date '+%Y-%m-%d %H-%M-%S')

echo "REPORTE DE ESTADO DE LA MAQUINA - $fecha"
usodisco=$(df / | grep / | awk '{ print $5 }' | sed 's/%//g')
echo -n "DISCO: "
if [ "$usodisco" -gt 85 ]; then
    echo "PELIGRO EL DISCO ESTA LLENO CON $usodisco "
else
    echo "EL DISCO ES LIVIANO CON $usodisco"
fi

echo -n "MEMORIA:"
memoriatotal=$(free -m | awk '/Mem:/ { print $2 }')
memoriausada=$(free -m | awk '/Mem:/ { print $3 }')
memoriaporcen=$(( 100 * memoriausada / memoriatotal ))
echo " ${memoriaporcen}% en uso ($memoriausada MB / $memoriatotal MB)"


